# Generated by Django 5.0.6 on 2024-07-10 10:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0002_skycolor_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skycolor',
            name='date_added',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
