# Generated by Django 5.0.6 on 2024-07-10 10:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0003_alter_skycolor_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skycolor',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
