# Generated by Django 5.0.6 on 2024-07-11 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0005_photocertificate_season_skyreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='sky_varities',
            new_name='sky_varieties',
        ),
    ]
